# Generated by Django 5.0.7 on 2025-01-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("cover", models.ImageField(upload_to="books_images/%Y/%m/%d/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.IntegerField(null=True)),
                ("pages", models.IntegerField(null=True)),
                ("binding", models.TextField(max_length=50, null=True)),
                ("format", models.TextField(max_length=50, null=True)),
                ("isbn", models.IntegerField(null=True)),
                ("weight", models.IntegerField(null=True)),
                ("for_age", models.IntegerField(null=True)),
                ("in_stock", models.IntegerField(null=True)),
                ("active", models.BooleanField(default=False)),
                ("rating", models.IntegerField(null=True)),
                ("data_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("data_changed", models.DateTimeField(auto_now=True, null=True)),
                (
                    "athor",
                    models.ManyToManyField(to="catalog.athor", verbose_name="arthor"),
                ),
                (
                    "genre",
                    models.ManyToManyField(to="catalog.genres", verbose_name="genre"),
                ),
                (
                    "publishing",
                    models.ManyToManyField(
                        to="catalog.publishing", verbose_name="publishing"
                    ),
                ),
                (
                    "seria",
                    models.ManyToManyField(to="catalog.series", verbose_name="seria"),
                ),
            ],
        ),
    ]
