# Generated by Django 5.0.7 on 2024-07-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="description",),
        migrations.AddField(
            model_name="book", name="active", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="athor",
            field=models.ManyToManyField(to="catalog.athor", verbose_name="arthor"),
        ),
        migrations.AddField(
            model_name="book",
            name="binding",
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book", name="data", field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="data_changed",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="data_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="book", name="for_age", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="format",
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(to="catalog.genres", verbose_name="genre"),
        ),
        migrations.AddField(
            model_name="book", name="in_stock", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="book", name="isbn", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="book", name="pages", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="publishing",
            field=models.ManyToManyField(
                to="catalog.publishing", verbose_name="publishing"
            ),
        ),
        migrations.AddField(
            model_name="book", name="rating", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="seria",
            field=models.ManyToManyField(to="catalog.series", verbose_name="seria"),
        ),
        migrations.AddField(
            model_name="book", name="weight", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                upload_to="books_images/%Y/%m/%d/", verbose_name="Book cover"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
