# Generated by Django 5.0.7 on 2024-07-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(upload_to="books_images/%Y/%m/%d/"),
        ),
    ]
