# Generated by Django 5.0.7 on 2024-08-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="email",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="phone",
            field=models.IntegerField(null=True),
        ),
    ]
