# Generated by Django 5.0.7 on 2024-08-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customerprofile_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="country",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="index",
            field=models.IntegerField(blank=True, null=True, verbose_name="Index"),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="information_to_know",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Information to know"
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="street_house",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Street, house"
            ),
        ),
    ]
