# Generated by Django 5.0.7 on 2024-11-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customerprofile_city_customerprofile_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="information_to_know",
            field=models.TextField(
                blank=True, max_length=50, null=True, verbose_name="Information to know"
            ),
        ),
    ]
