# Generated by Django 5.0.7 on 2024-08-18 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 8, 18, 16, 47, 14, 521779, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
