# Generated by Django 5.0.7 on 2024-08-21 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_bookincart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=16, verbose_name="Phone")),
                ("adress", models.CharField(max_length=100, verbose_name="Adress")),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order",
                        to="orders.cart",
                    ),
                ),
            ],
        ),
    ]
