# Generated by Django 5.0.7 on 2025-05-25 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_data',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 14, 13, 47, 807126)),
        ),
    ]
