# Generated by Django 5.0.7 on 2025-05-25 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_data_created_order_delivery_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ASMB', 'Assembling'), ('OTW', 'On the way'), ('RDY', 'Ready')], max_length=150, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_data',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 16, 23, 41, 656474)),
        ),
    ]
