# Generated by Django 5.0.7 on 2025-09-08 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status_alter_order_delivery_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_data',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 10, 20, 23, 32, 802638)),
        ),
    ]
