services:

  postgres:
    image: postgres:17
    container_name: bookstore_db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
     POSTGRES_DB: ${DATABASE_NAME}
     POSTGRES_USER: ${DATABASE_USERNAME}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  web:
    image: bookstore:latest
    container_name: bookstore_web
    ports:
      - 5000:5000
    depends_on:
      - postgres
    volumes:
      - static:/bookstore/src/static
      - media:/bookstore/src/media
    env_file:
      - .env
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
      - static:/bookstore/src/static
      - media:/bookstore/src/media
    depends_on:
      - web
      
volumes:
  static:
  media:
  db: