services:

  postgres:
    image: postgres:17
    container_name: bookstore_db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    image: bookstore:latest
    container_name: bookstore_web
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - .:/bookstore/src
      - static:/bookstore/static
      - media:/bookstore/media
    env_file:
      - .env
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
      - static:/bookstore/static
      - media:/bookstore/media
    depends_on:
      - web
      
volumes:
  static:
  media:
  db:
